services:
  - type: web
    name: auth-sync-service-dev
    runtime: docker
    plan: free
    region: frankfurt
    branch: dev
    dockerfilePath: ./deploy/Dockerfile
    envVars:
      - key: REDIS_URL
        fromService:
          name: redis
          type: redis
          property: connectionString

  - type: redis
    name: redis
    region: frankfurt
    plan: free
    maxmemoryPolicy: noeviction
    ipAllowList: []
